version: '3.8'

services:
  web:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always
    container_name: nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    restart: always
    container_name: app

  db:
    image: postgres:14.4
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_INITDB_ARGS= --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "8081:5432"
    container_name: db
